apiVersion: apps/v1
kind: Deployment
metadata:
  name: truyumwebapplicationdeployment
  labels:
    app: truYumWebApplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truYumWebApplication
  template:
    metadata: 
      labels:
        app: truYumWebApplication
      spec:
        containers:
          name: truYumWebApplication
          image: truyum.azurecr.io/new:latest
          ports:
            containerPort: 8080
        imagePullSecrets:
           name: truyumconsvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: truYumConSvcService
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: truYumWebApplication